Setup sqlite database
framgia/sph_flutter-capstone pull request #8
Opened 2022-04-20 10:34 UTC by erronerron

## Related Links:
- Issue link: https://www.notion.so/Setup-initial-DB-settings-c469f7fd9fdd4cbfa25a137ec7e92cfb

## Definition of Done
- [x] Setup sqlite database

## Notes:
- N/A

## Screenshots
![2022-04-20 18-30-46](https://user-images.githubusercontent.com/88467532/164212506-619ab7fa-c836-4e2c-bfe8-d3f4af9e7447.png)

## Test View  Points
- [ ] Setup sqlite database

2022-04-21 04:34 UTC, AubreyV approved these changes
## Approved
DB can be seen
Tables are complete
Schema is same with ERD
<img width="388" alt="image" src="https://user-images.githubusercontent.com/21002044/164372732-07002631-58ca-41cf-b28b-96fdaa6ef7c6.png">

2022-04-21 16:05 UTC, inahsanjuan requested changes
@erronerron 
After updating code comments, please run 
```
flutter format . 
```

2022-04-21 16:05 UTC, inahsanjuan commented on lib/models/model.dart
> +    ]);
```suggestion
    ],);
```

2022-04-21 16:05 UTC, inahsanjuan commented on lib/models/model.dart
> +    ]);
```suggestion
    ],);
```

2022-04-21 16:05 UTC, inahsanjuan commented on lib/models/model.dart
> +    ]);
```suggestion
    ],);
```

2022-04-21 16:05 UTC, inahsanjuan commented on lib/models/model.dart
> +    ]);
```suggestion
    ],);
```

2022-04-21 16:05 UTC, inahsanjuan commented on lib/models/model.dart
> +    bundledDatabasePath: null);
```suggestion
    bundledDatabasePath: null,);
```

2022-04-22 01:03 UTC, inahsanjuan approved these changes
Comments: 2 (Compiled)
Review time: 20 minutes

2022-04-22 01:03 UTC, merged